POST http://localhost:3001/jobs
Content-Type: application/json

{ "type": "sync-radarr" }

###

POST http://localhost:3001/jobs
Content-Type: application/json

{ "type": "sync-sonarr" }

###

GET  http://localhost:3001/files?mediaId=12

###

GET  http://localhost:3001/medias

###

GET https://radarr.choupibebz.online/MediaCover/18/poster-500.jpg
x-api-key: ec49424635564f45a9b8104366af0f8d